# Generated by Django 6.0.4 on 2026-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, verbose_name='Название'),
        ),
    ]
