# Generated by Django 6.0.4 on 2026-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_content_alter_question_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Название'),
        ),
    ]
